 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package veterinaria;

import controladores.AuthController;
import javax.swing.ImageIcon;
import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author FERNANDA
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setTitle("inicio de sesion");
        ImageIcon UsuarioIcono=
                new ImageIcon(getClass()
                        .getResource("../imagenes/fer.png"));
        Image img = UsuarioIcono.getImage();
        Image imgEscalada = 
            img.getScaledInstance(
                      imagenusuario.getWidth()
                    , imagenusuario.getHeight()
                    , Image.SCALE_SMOOTH);
   
    imagenusuario.setIcon(new ImageIcon(imgEscalada));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        LOGIN = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtcontrasenia = new javax.swing.JPasswordField();
        TXTUSUARIO = new javax.swing.JLabel();
        TXTCONTRASEÑA = new javax.swing.JLabel();
        BTNREGISTRARSE = new javax.swing.JButton();
        BTNINGRESAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        imagenusuario = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("lbliamgenusuario"); // NOI18N

        LOGIN.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        LOGIN.setText("LOGIN");

        txtusuario.setName("txtusuario"); // NOI18N
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });

        txtcontrasenia.setText("jPasswordField1");
        txtcontrasenia.setName("txtcontrasenia"); // NOI18N
        txtcontrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraseniaActionPerformed(evt);
            }
        });

        TXTUSUARIO.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        TXTUSUARIO.setText("USUARIO:");
        TXTUSUARIO.setName("TXTUSUARIO"); // NOI18N

        TXTCONTRASEÑA.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        TXTCONTRASEÑA.setText("CONTRASEÑA: ");
        TXTCONTRASEÑA.setName("txtcontrasenia"); // NOI18N

        BTNREGISTRARSE.setBackground(new java.awt.Color(240, 128, 128));
        BTNREGISTRARSE.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        BTNREGISTRARSE.setText("REGISTRARSE ");
        BTNREGISTRARSE.setName("BTNREGISTRARSE"); // NOI18N
        BTNREGISTRARSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGISTRARSEActionPerformed(evt);
            }
        });

        BTNINGRESAR.setBackground(new java.awt.Color(240, 128, 128));
        BTNINGRESAR.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        BTNINGRESAR.setText("INGRESAR");
        BTNINGRESAR.setName("BTNINGRESAR"); // NOI18N
        BTNINGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNINGRESARActionPerformed(evt);
            }
        });

        jLabel1.setName("lblimgusuario"); // NOI18N

        imagenusuario.setText("img");
        imagenusuario.setName("lblimagenususario"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagenusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(LOGIN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTUSUARIO)
                            .addComponent(TXTCONTRASEÑA)
                            .addComponent(txtcontrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(BTNREGISTRARSE)
                        .addGap(67, 67, 67)
                        .addComponent(BTNINGRESAR)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagenusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LOGIN)
                .addGap(18, 18, 18)
                .addComponent(TXTUSUARIO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TXTCONTRASEÑA)
                .addGap(18, 18, 18)
                .addComponent(txtcontrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNREGISTRARSE)
                    .addComponent(BTNINGRESAR))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void BTNREGISTRARSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTRARSEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNREGISTRARSEActionPerformed

    private void BTNINGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNINGRESARActionPerformed
        //ingresar todos los datos de usuario y contrasenia
        // al controlador para verificar si esta o np
        //registrado
        String usuario=txtusuario.getText();
        String contrasenia=
                new String(txtcontrasenia.getPassword());
        if(AuthController.autenticar(
                new modelos.usuario(usuario, contrasenia))
                ){
            JOptionPane.showMessageDialog(
            this,"Inicio de session exitoso");
        //abrir el dashborad
        new DashBoard().setVisible(true);
        //cerrar la ventana del login
        this.dispose();
    }else{
    JOptionPane.showMessageDialog(this,"Credenciales incorrectas");

        }
    }//GEN-LAST:event_BTNINGRESARActionPerformed

    private void txtcontraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNINGRESAR;
    private javax.swing.JButton BTNREGISTRARSE;
    private javax.swing.JLabel LOGIN;
    private javax.swing.JLabel TXTCONTRASEÑA;
    private javax.swing.JLabel TXTUSUARIO;
    private javax.swing.JLabel imagenusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtcontrasenia;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
